version: "3.8"

services:
  db:
    build: ./postgres
    container_name: db
    env_file:
      - .env.local
    environment:
      POSTGRES_user: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    build: ./adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  postgres_data:
