version: '3.8'
services:
    db:
        build: ./postgres
        env_file :
          - .env
          - .env.local
       # wokdir: /var/lib
        environment :
          # - POSTGRES_USER = user
          # - POSTGRES_PASSWORD = password
          # - POSTGRES_DB = database
            POSTGRES_user: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
             - 5432:5432
        container_name: postgres
   # adminer:
        #image: adminer
       # ports: 
           # - 8000:80
        #depends_on :
           #q - db