version: '3.7'

services:
  php:
    build: ./postgres
    
    volumes:
      - ./symfonyProject:/symfonyProject
    networks:
      - app-network

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
