version: '3.7'

services:
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: toto #a modifier via .env pas de pswd en clair
    networks:
      - backend

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - postgres

networks:
  backend:
    external: true
volumes:
  pgdata: