version: '3.8'

services:
  db:
    build: ./postgres
    container_name: db
    env_file:
      - .env.local
    environment:
      POSTGRES_user: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  #adminer:
    #image: adminer
    #ports: 
        #- 8000:80
    #depends_on :
        #- db