version: '3.8'

services:
  symfony:
    build: .
    volumes:
      - ./symfonyDockerCompose:/symfonyProject
    ports:
      - "8000:8000"
    networks:
      - backend

  composer:
    image: jabsraighs/ulysse_composer_alpine
    volumes:
      - ./symfony/:/volume/symfonyProject
    networks:
      - backend

networks:
  backend:
    external: true
