version: '3.8'

services:
  symfony:
    build: ./symfony
    volumes:
      - ./symfonyDockerCompose:/symfonyProject
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - backend

  composer:
    image: ./composer
    volumes:
      - ./symfony/:/volume/symfonyProject
    networks:
      - backend

networks:
  backend:
    external: true